# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.
CC = gcc
AR = ar
CFLAGS = -I.. -I../include -Iinclude # -g -DFUSE_VERSION_2_5=1 -DDEBUG=1 
LIBS = -L../lib -lanxt -lanxtnet
PREFIX = /usr/local
PATH_BIN =     $(PREFIX)/bin
PATH_LIB =     $(PREFIX)/lib
PATH_INCLUDE = $(PREFIX)/include
PATH_MAN =     $(PREFIX)/man
NXTD_PIDFILE = /var/run/nxtd.pid

CONFIG_CFLAGS =
CONFIG_LIBS = -lanxt -lanxtnet
CONFIG_STATIC_LIBS = -lanxt -lanxtnet
CONFIG_VERSION = 0.10

# USB modules: libusb, dummy
USB_MOD = libusb

# Bluetooth modules: bluez, dummy
BT_MOD  = bluez
