# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

-include Makefile.config

all:
	make -C libanxt/
	make -C libanxt_file/
	make -C libanxt_net/
	make -C libanxt_tools/
	make -C nxtd/
	make -C examples/
	make -C tools/

##### Install target #####

installfiles:
	mkdir -p $(PATH_LIB)
	cp -R lib/* $(PATH_LIB)
	mkdir -p $(PATH_INCLUDE)
	cp -R include/* $(PATH_INCLUDE)
	mkdir -p $(PATH_BIN)
	cp -R bin/* $(PATH_BIN)
	mkdir -p $(PATH_MAN)
	cp -R doc/man/* $(PATH_MAN)
	sh tools/anxt-config-creator.sh $(PREFIX) > $(PATH_BIN)/anxt-config
	chmod 755 $(PATH_BIN)/anxt-config

install: installfiles
	ln -sf $(PATH_LIB)/libanxt.so.1 $(PATH_LIB)/libanxt.so
	ln -sf $(PATH_LIB)/libanxttools.so.1 $(PATH_LIB)/libanxttools.so
	ln -sf $(PATH_LIB)/libanxtfile.so.1 $(PATH_LIB)/libanxtfile.so
	ln -sf $(PATH_LIB)/libanxtnet.so.1 $(PATH_LIB)/libanxtnet.so

##### Build distributable archive

tar.gz:
	(set -x;ANXT=aNXT-`bin/anxt-config --version` && rm -rf /tmp/$$ANXT && mkdir /tmp/$$ANXT && tar -cvf - * | (cd /tmp/$$ANXT && tar -xf -) && (cd /tmp/$$ANXT && make realclean && cd .. && tar -cf $$ANXT.tar $$ANXT && gzip -9f $$ANXT.tar))

##### Clean target #####

clean:
	make -C libanxt/ clean
	make -C libanxt_file/ clean
	make -C libanxt_net/ clean
	make -C libanxt_tools/ clean
	make -C nxtd/ clean
	make -C examples/ clean
	make -C tools/ clean

realclean: clean
	(find . -name .svn -print | xargs rm -rf)

# (header) dependencies generated by "gcc -MM -Iinclude *.c"
cal.o: cal.c include/nxtfile/cal.h
mkfont.o: mkfont.c
nvconfig.o: nvconfig.c include/nxtfile/nvconfig.h
nxt.o: nxt.c include/nxtnet.h include/nxt.h
nxtcam.o: nxtcam.c include/nxt.h include/nxtnet.h \
  include/nxt_i2c/nxtcam.h
nxtd_bt_bluez.o: nxtd_bt_bluez.c nxtd.h nxtd_bt_bluez.h
nxtd_bt_dummy.o: nxtd_bt_dummy.c nxtd.h
nxtd.o: nxtd.c include/nxtnet.h nxtd.h
nxtdisplay.o: nxtdisplay.c include/nxt.h include/nxtnet.h \
  include/nxtdisplay.h include/nxt.h
nxtd_usb_dummy.o: nxtd_usb_dummy.c nxtd.h
nxtd_usb_libusb.o: nxtd_usb_libusb.c nxtd.h nxtd_usb_libusb.h
nxtnet.o: nxtnet.c include/nxtnet.h
nxttools.o: nxttools.c include/nxttools.h include/nxt.h include/nxtnet.h
ric.o: ric.c include/nxtfile/ric.h
rmd.o: rmd.c
rso.o: rso.c include/nxtfile/rso.h
us.o: us.c include/nxt.h include/nxtnet.h include/nxt_i2c/us.h
