# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

-include Makefile.config

all: lib/libnxt.a lib/libnxttools.a lib/libnxtfile.a lib/libnxtnet.a bin/nxtd
	make -C examples/
	make -C tools/

##### Make libnxt #####

lib/libnxt.a: nxt.o us.o nxtcam.o
	$(AR) rs $@ $^
	$(CC) -shared -Wl,-soname,libnxt.so.1 -o lib/libnxt.so.1 $^ -lc

nxt.o: nxt.c
	$(CC) $(CFLAGS) -c -o $@ $< -DNXTD_PIDFILE=\"$(NXTD_PIDFILE)\" -DPATH_BIN=\"$(PATH_BIN)\"

us.o: us.c
	$(CC) $(CFLAGS) -c -o $@ $<

nxtcam.o: nxtcam.c
	$(CC) $(CFLAGS) -c -o $@ $<

##### Make libnxttools #####

lib/libnxttools.a: nxttools.c
	$(CC) $(CFLAGS) -c -o nxttools.o $<
	$(AR) rs $@ nxttools.o
	$(CC) -shared -Wl,-soname,libnxttools.so.1 -o lib/libnxttools.so.1 nxttools.o -lc

##### Make libnxtfile #####

lib/libnxtfile.a: cal.o ric.o rmd.o rso.o nvconfig.o
	$(AR) rs $@ $?
	$(CC) -shared -Wl,-soname,libnxtfile.so.1 -o lib/libnxtfile.so.1 $^ -lc

cal.o: cal.c
	$(CC) $(CFLAGS) -c -o $@ $<

ric.o: ric.c
	$(CC) $(CFLAGS) -c -o $@ $<

rmd.o: rmd.c
	$(CC) $(CFLAGS) -c -o $@ $<

rso.o: rso.c
	$(CC) $(CFLAGS) -c -o $@ $<

nvconfig.o: nvconfig.c
	$(CC) $(CFLAGS) -c -o $@ $<

##### Make nxtd #####

bin/nxtd: nxtd.c nxtd_usb_$(USB_MOD).c nxtd_bt_$(BT_MOD).c lib/libnxtnet.a
	$(CC) $(CFLAGS) -o $@ nxtd.c nxtd_usb_$(USB_MOD).c nxtd_bt_$(BT_MOD).c -Llib/ -lusb -lbluetooth -lnxtnet -DNXTD_PIDFILE=\"$(NXTD_PIDFILE)\"

##### Make nxtnet #####

lib/libnxtnet.a: nxtnet.c
	$(CC) $(CFLAGS) -c -o nxtnet.o $<
	$(AR) rs $@ nxtnet.o
	$(CC) -shared -Wl,-soname,libnxtnet.so.1 -o lib/libnxtnet.so.1 nxtnet.o -lc

##### Install target #####

install:
	cp -R lib/* $(PATH_LIB)
	ln -sf $(PATH_LIB)/libnxt.so.1 $(PATH_LIB)/libnxt.so
	ln -sf $(PATH_LIB)/libnxttools.so.1 $(PATH_LIB)/libnxttools.so
	ln -sf $(PATH_LIB)/libnxtfile.so.1 $(PATH_LIB)/libnxtfile.so
	cp -R include/* $(PATH_INCLUDE)
	cp -R bin/* $(PATH_BIN)
	cp -R doc/man/* $(PATH_MAN)

##### Clean target #####

clean:
	rm -Rf *.o lib/* bin/nxtd
	make -C examples/ clean
	make -C tools/ clean

# (header) dependencies generated by "gcc -MM -Iinclude *.c"
cal.o: cal.c include/nxtfile/cal.h
nvconfig.o: nvconfig.c include/nxtfile/nvconfig.h
nxt.o: nxt.c include/nxtnet.h include/nxt.h
nxtcam.o: nxtcam.c include/nxt.h include/nxtnet.h \
  include/nxt_i2c/nxtcam.h
nxtd_bt_bluez.o: nxtd_bt_bluez.c nxtd.h
nxtd_bt_dummy.o: nxtd_bt_dummy.c nxtd.h
nxtd.o: nxtd.c include/nxtnet.h nxtd.h
nxtd_usb_dummy.o: nxtd_usb_dummy.c nxtd.h
nxtd_usb_libusb.o: nxtd_usb_libusb.c nxtd.h
nxtnet.o: nxtnet.c include/nxtnet.h
nxttools.o: nxttools.c include/nxttools.h include/nxt.h include/nxtnet.h
ric.o: ric.c include/nxtfile/ric.h
rmd.o: rmd.c
rso.o: rso.c include/nxtfile/rso.h
us.o: us.c include/nxt.h include/nxtnet.h include/nxt_i2c/us.h
