#!/bin/sh
set -e
#if [ "$1" = "configure" ]; then
#	if [ -d /usr/doc -a ! -e /usr/doc/anxt -a -d /usr/share/doc/anxt ]; then
#		ln -sf ../share/doc/anxt /usr/doc/anxt
#	fi
#fi
if test -x /usr/bin/update-menus; then 
   update-menus
fi
