# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

nxt_server_usage_example: nxt_server_usage_example.adb
	gnat make -g nxt_server_usage_example.adb

clean:
	rm -f nxt_server_usage_example nxt_server_usage_example.ali \
              nxt_server_usage_example.o \
              b~nxt_server_usage_example.adb  b~nxt_server_usage_example.ads \
              b~nxt_server_usage_example.ali  b~nxt_server_usage_example.o
