# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

-include ../Makefile.config

all: 
	make -C c/
	make -C server/

clean:
	make -C c/ clean
	make -C server/ clean

